eComerce_site/app_cart/urls.py
from unicodedata import name
from django.urls import path
from app_cart import views

app_name = "app_cart"

urlpatterns = [
    path('add/<int:pk>/', views.addToCartView, name="add"),
    path('cart/', views.cartView, name="cart"),
    path('remove/<int:pk>/', views.removeFromCartView, name="remove"),
    path('increase/<int:pk>/', views.increaseCartView, name="increase"),
    path('decrease/<int:pk>/', views.decreaseCartView, name="decrease"),
    path('coupon/', views.couponsView, name="coupon"),
    path('add-bronze/', views.addBronzeView, name="addBronze"),
    path('remove-bronze/', views.removeBronzeView, name="removeBronze"),
]

eComerce_site/app_payment/urls.py
from django.urls import path
from app_payment import views

app_name = "app_payment"

urlpatterns = [
    path("checkout/", views.billingView, name="checkout"),
    path("payment/", views.paymentView, name="payment"),
    path("pay-urls/", views.completeView, name="complete"),
    path("purchase/<val_id>/<tran_id>/", views.purchasedView, name="purchase"),
    path("purchase_list/", views.orderedView, name="purchased"),
]

eComerce_site/app_shop/urls.py
from django.urls import path
from app_shop import views

app_name = "app_shop"

urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("product-details/<int:pk>", views.ProductView.as_view(), name="productDetails"),
    path("new-product/", views.addProductView, name="newProduct"),
]

eComerce_site/app_user/urls.py
from django.urls import path
from app_user import views

app_name = "app_user"

urlpatterns = [
    path('registration/', views.registrationView, name="registration"),
    path('login/', views.loginView, name="login"),
    path('logout/', views.logoutView, name="logout"),
    path('profile/', views.userProfileView, name="profile"),
]

eComerce_site/eComerce_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_shop.urls')),
    path('user/', include('app_user.urls')),
    path('shop/', include('app_cart.urls')),
    path("pay/", include("app_payment.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eComerce_site/templates/base.html
<!doctype html>
{% load static %}
{% load myTags %}
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'cssFiles/myStyle.css' %}">

  <title>{% block title_block %}eCommerce Site{% endblock title_block %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark myNavBackground sticky-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'app_shop:home' %}"><img id="brand" src="/media/nav_brand.png"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'app_shop:home' %}">Home</a>
          </li>

          <!-- Vendor's shop options -->
        {% if user.is_authenticated and user.account_type == "Vendor" %}
        <div class="nav-item dropdown mx-md-3">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fab fa-product-hunt fs-5"></i> Products
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'app_shop:newProduct' %}">Add Product</a></li>
            <li><a class="dropdown-item" href="{% url 'app_user:profile' %}">My Products</a></li>
            <li><a class="dropdown-item" href="{% url 'app_payment:purchased' %}">Sold Products</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class='dropdown-item' href="{% url 'app_user:logout' %}">Delete Product</a></li>
          </ul>
        </div>
        {% endif %}

        </ul>

        <form class="d-flex">
          <input class="form-control me-md-2" type="search" placeholder="Search.." aria-label="Search">
          <button class="btn btn-success" type="submit">Search</button>
        </form>

        {% if user.is_authenticated %}
        <div class="nav-item dropdown mx-md-3">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user-tie fs-5"></i> {{request.user.userProfile.username}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'app_user:profile' %}">View Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'app_user:profile' %}">Edit Profile</a></li>
            <li><a class="dropdown-item" href="{% url 'app_payment:purchased' %}">Purchased items</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class='dropdown-item' href="{% url 'app_user:logout' %}">Logout</a></li>
          </ul>
        </div>

        <div>
          <div class="faIconsNav me-md-3"><a href="{% url 'app_cart:cart' %}">
            <i class="fs-2 fa fa-shopping-cart text-light"></i>
            <span class="top-0 start-100 translate-middle badge rounded-pill bg-dark">
              {{ request.user|cart_total }}
              <span class="visually-hidden">total cart item</span>
            </span>
          </a></div>
        </div>
        {% else %}
        <div class="nav-item dropdown mx-md-3">
          <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user-tie fs-5"></i> Sign in
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'app_user:registration' %}">Registration</a></li>
            <li><a class="dropdown-item" href="{% url 'app_user:login' %}">Log in</a></li>
          </ul>
        </div>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class='container'>

    <div class="mt-2">
      {% if messages %}
      {% for message in messages %}
      <div {% if message.tags %}class="alert alert-{{message.tags}} alert-dismissible fade show" {% else
        %}class="alert alert-warning alert-dismissible fade show" {% endif %} role="alert" id="success-alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
      {% endif %}
    </div>


    {% block body_block %}{% endblock body_block %}
  </div>

  <section class="container-fluid myBackground">
    <div class="container">
      <div class="row">
        <div class="col text-center">
          <div class="faIcons mx-md-3">
            <a class="text-decoration-none" href="https://www.youtube.com/channel/UCNtkG_b2gGjUqmyNI9RL3uQ"><i
                class="fab fa-youtube text-danger"></i></a>
          </div>
          <div class="faIcons mx-md-3">
            <a class="text-decoration-none" href="https://www.facebook.com/AhMunna7x/"><i
                class="fab fa-facebook-square text-white"></i></a>
          </div>
          <div class="faIcons mx-md-3">
            <a class="text-decoration-none" href="https://twitter.com/munna_ahsanul"><i
                class="fab fa-twitter text-info"></i></a>
          </div>
          <div class="faIcons mx-md-3">
            <a class="text-decoration-none" href="https://github.com/AH-Munna"><i
                class="fab fa-github text-white"></i></a>
          </div>
        </div>
      </div>
      <div class="row text-center text-white">
        <div class="col">
          <label for="text" class="unselectable">&copy; Copyrights of Ahsanul Haque Munna</label><br>
          <label for="text" class="unselectable">All Rights Reserved</label>
        </div>
      </div>
    </div>
  </section>

  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  <script src="https://kit.fontawesome.com/6bc1f6930c.js" crossorigin="anonymous"></script>

  {% comment %} my script {% endcomment %}
  <script src="{% static 'jsFiles\myScript.js' %}"></script>
</body>

</html>

eComerce_site/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
<h2>Featured product</h2>
<div class="row">
    {% for product in object_list %}
    <div class="col-md-6 col-sm-12 col-xl-4 col-xxl-3">
        
        <figure class="shadow p-2">
            <div class="">
                <img class="" src="/media/{{product.product_image}}" alt="product image" style="width: 300px; height: 337px; object-fit: cover;">
            </div>
            <figcaption>
                <a class="text-decoration-none" href="{% url 'app_shop:productDetails' pk=product.pk %} "><h6 class="fs-5 text-center my-2">{{product.product_name}}</h6>
                    <div class="mt-3 text-dark">
                        <span>&#2547;{{product.product_price|floatformat:2}} </span>
                        {% if not product.old_price == 0.00 %}
                        <span> <del> &#2547;{{product.old_price|floatformat:2}}</del></span>
                        {% endif %}
                    </div>
                </a>
            </figcaption>
        </figure>

    </div>
    {% endfor %}
</div>

{% endblock body_block %}