VideoStreamingSite/VideoStreamingSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('video_app.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

VideoStreamingSite/video_app/urls.py
from django.urls import path
from video_app import views

app_name = "app_video"

urlpatterns = [
    path('registration/', views.registrationView, name='registration'),
    path('login/', views.loginFormView, name='login'),
    path('logout/', views.logoutView, name="logout"),
    path('', views.homepageView, name="home"),
    path('upload/', views.uploadVideoView, name='upload'),
    path('video/<int:pk>', views.videoView, name='video')
]

VideoStreamingSite/video_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Video(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="uploader", default='1')

    CATEGORY_CHOICES = [
        ('ALL', 'All category'),
        ('SCIENCE', 'Science'),
        ('GAMING', 'Gaming'),
        ('MOVIES', 'Movies'),
    ]
    video_category = models.CharField(max_length=64, choices=CATEGORY_CHOICES, default='ALL')

    video_link = models.CharField(max_length=2048)
    video_title = models.CharField(max_length=264, default='title')
    video_upload_date = models.DateTimeField(auto_now_add=True)
    video_description = models.TextField(blank=True)

    class Meta:
        ordering = ('-video_upload_date',)

class Comment(models.Model):
    video = models.ForeignKey(Video, related_name='video_comment', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name= "commenter", on_delete=models.CASCADE)
    comment = models.TextField()
    comment_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('comment_date',)

    def __str__(self) -> str:
        return self.comment

VideoStreamingSite/video_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from video_app.models import Video, Comment

class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(required=True, label="User Name", widget=forms.TextInput(attrs={'placeholder':"username....", "class": "mb-3"}))
    email = forms.EmailField(required=True, label="Email Address", widget=forms.TextInput(attrs={'placeholder':"email....", "class": "mb-3"}))
    password1 = forms.CharField(required=True, label="Password", widget=forms.PasswordInput(attrs={'placeholder':"password....", "class": "mb-3"}))
    password2 = forms.CharField(required=True, label="Enter Password again", widget=forms.PasswordInput(attrs={'placeholder':"re type password...."}))

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

        #labels = {"username": "User Name", "password2": "Enter password again"}

class VideoUploadForm(forms.ModelForm):
    video_link = forms.CharField(required=True, label="Embeded video link", widget=forms.TextInput(attrs={'placeholder':"copy embeded link from video share option"}))
    video_title = forms.CharField(required=True, label="Title for your video", widget=forms.TextInput(attrs={'placeholder':"video title.........."}))
    class Meta:
        model = Video
        fields = ("video_category", "video_link", "video_title", "video_description", )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment", )

        labels = {'comment': "Your opinion of the video"}

VideoStreamingSite/video_app/views.py
from cmath import log
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import HttpResponseRedirect
from video_app.models import Video, Comment
from video_app.forms import CommentForm, UserRegistrationForm, VideoUploadForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.db.models import Q

# Create your views here.
def registrationView(request):
    form = UserRegistrationForm()
    registered = False

    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            registered = True
            return HttpResponseRedirect(reverse('app_video:login'))

    return render(request, 'video_app/user_registration.html', context={'title': "New User", "form": form, "registered": registered})

def loginFormView(request):
    form = AuthenticationForm()
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('app_video:home'))
    return render(request, "video_app/user_login.html", context={'title': "User Login", "form": form})

@login_required
def logoutView(request):
    logout(request)
    return HttpResponseRedirect(reverse('app_video:login'))

@login_required
def homepageView(request):
    all_videos = Video.objects.all

    if request.method == "GET":
        search = request.GET.get("search", '')
        search_result = Video.objects.filter(Q(video_title__icontains=search) | Q(video_category__icontains=search))
        # search_result2 = User.objects.filter( first_name__icontains=search)
        # search_result3 = User.objects.filter( last_name__icontains=search)
        #search_result2 = UserProfile.objects.filter( full_name__icontains=search)
        #return HttpResponseRedirect(reverse('app_post:home'))

    dict = {
        "title": "Home Page",
        "video_list": all_videos,
        "search": search,
        "search_result": search_result
    }
    return render(request, 'index.html', context=dict)

def uploadVideoView(request):
    form = VideoUploadForm()

    if request.method == "POST":
        form = VideoUploadForm(request.POST)
        if form.is_valid():
            video_obj = form.save(commit=False)
            video_obj.user = request.user
            video_obj.save()

            return HttpResponseRedirect(reverse('app_video:home'))

    return render(request, 'video_app/upload_video.html', context={'title':"upload video", 'form': form})

def videoView(request, pk):
    video = Video.objects.get(pk=pk)

    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_obj = form.save(commit=False)
            comment_obj.user = request.user
            comment_obj.video = video
            comment_obj.save()
            return HttpResponseRedirect(reverse("app_video:video", kwargs={"pk": video.pk}))

    video.video_link = video.video_link.replace('width="560" height="315"', "width='100%' height='100%'")
    dict = {
        'title': video.video_title,
        'video': video,
        'form': form,
        'loggedInUser': request.user
    }
    return render(request, 'video_app/video_page.html', context=dict)

VideoStreamingSite/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'cssFiles/myStyle.css' %}">

    <title>{% block title_block %}Video Site{% endblock title_block %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border shadow-sm sticky-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'app_video:home' %}"><img id="brand" src="/media/nav_brand.png"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-5 mb-2 mb-lg-0">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Videos
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">My Videos</a></li>
                            <li><a class="dropdown-item" href="{% url 'app_video:upload' %}">Upload</a></li>
                            <li><a class="dropdown-item" href="#">Update</a></li>
                        </ul>
                    </li>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Profile
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="">View Profile</a></li>
                            <li><a class="dropdown-item" href="">Edit Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class='dropdown-item' href="{% url 'app_video:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Login
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'app_video:registration' %}">User Registration</a></li>
                            <li>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'app_video:login' %}">User login</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" name="search" type="search" placeholder="Title or Category..." aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class='container'>
        {% block body_block %}{% endblock body_block %}
    </div>

    <section class="container-fluid myBackground">
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <div class="faIcons mx-md-3">
                        <a class="text-decoration-none"
                            href="https://www.youtube.com/channel/UCNtkG_b2gGjUqmyNI9RL3uQ"><i
                                class="fab fa-youtube text-danger"></i></a>
                    </div>
                    <div class="faIcons mx-md-3">
                        <a class="text-decoration-none" href="https://www.facebook.com/AhMunna7x/"><i
                                class="fab fa-facebook-square text-white"></i></a>
                    </div>
                    <div class="faIcons mx-md-3">
                        <a class="text-decoration-none" href="https://twitter.com/munna_ahsanul"><i
                                class="fab fa-twitter text-info"></i></a>
                    </div>
                    <div class="faIcons mx-md-3">
                        <a class="text-decoration-none" href="https://github.com/AH-Munna"><i
                                class="fab fa-github text-white"></i></a>
                    </div>
                </div>
            </div>
            <div class="row text-center text-white">
                <div class="col">
                    <label for="text" class="unselectable">&copy; Copyrights of Ahsanul Haque Munna</label><br>
                    <label for="text" class="unselectable">All Rights Reserved</label>
                </div>
            </div>
        </div>
    </section>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    <script src="https://kit.fontawesome.com/6bc1f6930c.js" crossorigin="anonymous"></script>

    {% comment %} my script {% endcomment %}
    <script src="{% static 'jsFiles\myScript.js' %}"></script>
</body>

</html>

VideoStreamingSite/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}{{title}}{% endblock title_block %}

{% block body_block %}
{% if search %}
<center>
{% for video in search_result %}
    <a href="{% url 'app_video:video' pk=video.pk %}" class='text-decoration-none'>
        <div class="mt-5 fs-3 fw-b">User: {{video.user}}</div><br>
        <div class="">{{video.video_link|safe}}</div>
        <div class="fw-bold fs-4">{{video.video_title}}</div>
        <div class="fw-bold mb-3">Category: {{video.video_category}}</div>
        <div>upload date: {{video.video_upload_date}}</div>
    </a>
    <hr>
{% endfor %}
</center>
{% else %}
<center>
    <div class='col-md-6'>
        <h1 class="text-center my-5 display-4">All videos from all users</h1>
        {% for video in video_list %}
        <a href="{% url 'app_video:video' pk=video.pk %}" class='text-decoration-none'>
            <div class="mt-5 fs-3 fw-b">User: {{video.user}}</div><br>
            <div class="">{{video.video_link|safe}}</div>
            <div class="fw-bold fs-4">{{video.video_title}}</div>
            <div class="fw-bold mb-3">Category: {{video.video_category}}</div>
            <div>upload date: {{video.video_upload_date}}</div>
        </a>
        <hr>
        {% endfor %}
    </div>
</center>
{% endif %}
{% endblock body_block %}

VideoStreamingSite/templates/video_app/upload_video.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}{{title}}{% endblock title_block %}

{% block body_block %}
<center>
    <form class="col-md-6 px-4 my-5 py-5 shadow myform" method="POST">
        <h3 class="mb-4 text-info my-3">Upload a Video.</h3>
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-success px-4 my-2">Upload</button>
    </form>
</center>
{% endblock body_block %}

VideoStreamingSite/templates/video_app/user_login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}{{title}}{% endblock title_block %}

{% block body_block %}
<center>
    <form class="col-sm-4 px-4 my-5 py-5 shadow myform" method="POST">
        <h3 class="mb-4 text-info">Log in to access your account.</h3>
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-primary px-4 my-2">Log in</button>
    </form>
    <div>
        <p class="my-3">New user? Create an account<a class="text-decoration-none" href="{% url 'app_video:registration' %}"> here</a></p>
    </div>
</center>
{% endblock body_block %}

VideoStreamingSite/templates/video_app/user_registration.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}{{title}}{% endblock title_block %}

{% block body_block %}
<center>
    <form class="col-md-4 px-4 my-5 py-5 shadow myform" method="POST">
        <h3 class="mb-4 text-info">Create an account to view videos and comment.</h3>
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class="btn btn-outline-primary px-4 my-2">Sign up</button>
    </form>
    <div>
        <p class="my-3">Already have an account? <a class="text-decoration-none" href="{% url 'app_video:login' %}">Login here</a></p>
    </div>
</center>
{% endblock body_block %}

VideoStreamingSite/templates/video_app/video_page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}{{title}}{% endblock title_block %}

{% block body_block %}
    <div class="mt-5 fs-3 fw-b">Video Uploaded by: <a href="#" class="text-decoration-none">@{{video.user}}</a></div><br>
    <div class="ratio ratio-16x9">
        <div class="">{{video.video_link|safe}}</div>
      </div>
    <div class="fw-bold fs-4">{{video.video_title}}</div>
    <div class="fw-bold mb-3">Category: {{video.video_category}}</div>
    <div>{{video.video_upload_date}}</div>
    <div class="mt-3 mb-5">{{video.video_description}}</div>
    <hr>

    <div class="row my-5">
        <div class="col-md-6">
            <h5 class="display-5 text-center text-success my-4">All Comments</h5>
            <ul>
            {% for comment in video.video_comment.all %}
            <li class="my-3"><b>{{comment.user}}</b>: {{comment.comment}}<div class="my-1">{{comment.comment_date}}</div></li>
            {% endfor %}
            </ul>
        </div>
        <div class="col-md-6">
            <form class="my-5" method="POST">
                {{form|crispy}}
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-primary my-2 px-3">Comment as {{ loggedInUser }}</button>
            </form>
        </div>
    </div>
{% endblock body_block %}