eComerce_site/app_cart/urls.py
from unicodedata import name
from django.urls import path
from app_cart import views

app_name = "app_cart"

urlpatterns = [
    path('add/<int:pk>/', views.addToCartView, name="add"),
    path('cart/', views.cartView, name="cart"),
    path('remove/<int:pk>/', views.removeFromCartView, name="remove"),
    path('increase/<int:pk>/', views.increaseCartView, name="increase"),
    path('decrease/<int:pk>/', views.decreaseCartView, name="decrease"),
    path('coupon/', views.couponsView, name="coupon"),
    path('add-bronze/', views.addBronzeView, name="addBronze"),
    path('remove-bronze/', views.removeBronzeView, name="removeBronze"),
]

eComerce_site/app_payment/urls.py
from django.urls import path
from app_payment import views

app_name = "app_payment"

urlpatterns = [
    path("checkout/", views.billingView, name="checkout"),
    path("payment/", views.paymentView, name="payment"),
    path("pay-urls/", views.completeView, name="complete"),
    path("purchase/<val_id>/<tran_id>/", views.purchasedView, name="purchase"),
    path("purchase_list/", views.orderedView, name="purchased"),
]

eComerce_site/app_shop/urls.py
from django.urls import path
from app_shop import views

app_name = "app_shop"

urlpatterns = [
    path("", views.Home.as_view(), name="home"),
    path("product-details/<int:pk>", views.ProductView.as_view(), name="productDetails"),
    path("new-product/", views.addProductView, name="newProduct"),
]

eComerce_site/eComerce_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_shop.urls')),
    path('user/', include('app_user.urls')),
    path('shop/', include('app_cart.urls')),
    path("pay/", include("app_payment.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eComerce_site/app_cart/models.py
from django.db import models
from django.conf import settings
from app_shop.models import Product

# Create your models here.
class ShopCart(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="cartUser")
    item = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="cartItem")
    quantity = models.IntegerField(default=1)
    purchased = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return f'{self.quantity} X {self.item}'

    def get_total(self):
        return format(self.item.product_price * self.quantity, '0.2f')

class ShopOrder(models.Model):
    orderitems = models.ManyToManyField(ShopCart)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    payment_id = models.CharField(max_length=264, blank=True, null=True)
    orderId = models.CharField(max_length=264, blank=True, null=True)
    gold = models.IntegerField(default=0)
    bronze = models.IntegerField(default=0)

    def get_totals(self):
        total = 0
        for order_item in self.orderitems.all():
            total += float(order_item.get_total())
        total = total - (self.gold * 250)
        total = total - (self.bronze * 25)
        return total

eComerce_site/app_cart/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from app_cart.models import ShopCart, ShopOrder
from app_shop.models import Product

# Create your views here.
@login_required
def addToCartView(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_item = ShopCart.objects.get_or_create(item=item, user=request.user, purchased=False)
    order_obj = ShopOrder.objects.filter(user=request.user, ordered=False)

    if order_obj.exists():
        order = order_obj[0]
        if order.orderitems.filter(item=item).exists():
            order_item[0].quantity += 1
            order_item[0].save()
            messages.info(request, "Quantity of this item has been updated")
            return redirect("app_shop:home")
        else:
            order.orderitems.add(order_item[0])
            messages.info(request, "Item added to Cart.")
            return redirect("app_shop:home")
    else:
        order = ShopOrder(user=request.user)
        order.save()
        order.orderitems.add(order_item[0])
        messages.info(request, "Item added to Cart.")
        return redirect("app_shop:home")

@login_required
def cartView(request):
    carts = ShopCart.objects.filter(user=request.user, purchased=False)
    orders = ShopOrder.objects.filter(user=request.user, ordered=False)

    if carts.exists() and orders.exists():
        order = orders[0]

        dict = {
            "title": "Cart items",
            "carts": carts,
            "order": order,
            "gold": request.user.userProfile.coupons_gold,
            "bronze": request.user.userProfile.coupons_bronze,
        }
        return render(request, "app_cart/cart.html", context=dict)
    else:
        messages.warning(request, "You haven't added any item to cart")
        return redirect("app_shop:home")

@login_required
def removeFromCartView(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_obj = ShopOrder.objects.filter(user=request.user, ordered=False)
    if order_obj.exists():
        order = order_obj[0]
        if order.orderitems.filter(item=item).exists():
            order_item = ShopCart.objects.filter(item=item, user=request.user, purchased=False)
            order_item = order_item[0]
            order.orderitems.remove(order_item)
            order_item.delete()
            messages.warning(request, "item removed from cart")
            return redirect("app_cart:cart")
        else:
            messages.info(request, "no such item")
            return redirect("app_shop:home")
    else:
        messages.info(request, "no such item")
        return redirect("app_shop:home")

@login_required
def increaseCartView(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_obj = ShopOrder.objects.filter(user=request.user, ordered=False)
    if order_obj.exists():
        order = order_obj[0]
        if order.orderitems.filter(item=item).exists():
            order_item = ShopCart.objects.filter(item=item, user=request.user, purchased=False)[0]
            if order_item.quantity > 0:
                order_item.quantity += 1
                order_item.save()
                messages.info(request, f"{item.product_name}'s quantity increased")
                return redirect("app_cart:cart")
        else:
            messages.info(request, f"{item.product_name} is not in your cart")
            return redirect("app_shop:home")
    else:
        messages.info(request, "no such item")
        return redirect('app_shop:home')

@login_required
def decreaseCartView(request, pk):
    item = get_object_or_404(Product, pk=pk)
    order_obj = ShopOrder.objects.filter(user=request.user, ordered=False)
    if order_obj.exists():
        order = order_obj[0]
        if order.orderitems.filter(item=item).exists():
            order_item = ShopCart.objects.filter(item=item, user=request.user, purchased=False)[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
                messages.info(request, f"{item.product_name}'s quantity decreased")
                return redirect("app_cart:cart")
            else:
                return HttpResponseRedirect(reverse("app_cart:remove", kwargs={"pk":order_item.item.pk}))
                #return redirect("app_cart:remove", kwargs={"pk":order_item.item.pk})
        else:
            messages.info(request, f"{item.product_name} is not in your cart")
            return redirect("app_shop:home")
    else:
        messages.info(request, "no such item")
        return redirect('app_shop:home')

@login_required
def couponsView(request):
    order_obj = ShopOrder.objects.filter(user=request.user, ordered=False)[0]
    total_money = order_obj.get_totals()
    gold = request.user.userProfile.coupons_gold
    bronze = request.user.userProfile.coupons_bronze

    dict = {
        "title": "Use Coupons",
        "total": total_money,
        "gold": gold,
        "bronze": bronze,
        "usedBronze": ShopOrder.objects.filter(user=request.user, ordered=False)[0].bronze,
        "usedGold": ShopOrder.objects.filter(user=request.user, ordered=False)[0].gold,
    }
    return render(request, "app_cart/coupon.html", context=dict)

@login_required
def addGoldView(request):
    gold = request.user.userProfile.coupons_gold
    order_obj = ShopOrder.objects.filter(user=request.user, ordered=False)[0]
    total_money = order_obj.get_totals()

@login_required
def addBronzeView(request):
    profile = request.user.userProfile
    profile.coupons_bronze -= 1
    profile.save()

    order_obj = ShopOrder.objects.filter(user=request.user, ordered=False)[0]
    order_obj.bronze += 1
    order_obj.save()

    return redirect("app_cart:coupon")
    
@login_required
def removeBronzeView(request):
    profile = request.user.userProfile
    profile.coupons_bronze += 1
    profile.save()

    order_obj = ShopOrder.objects.filter(user=request.user, ordered=False)[0]
    order_obj.bronze -= 1
    order_obj.save()

    return redirect("app_cart:coupon")

    

eComerce_site/templates/app_cart/cart.html
{% extends 'base.html' %}
{% block title_block %}{{title}}{% endblock title_block %}

{% block body_block %}
<div class="my-5">
    <div class="my-5">
      <h2>Your Cart</h2>
    </div>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col" width="15%">#</th>
          <th scope="col">Product Name</th>
          <th scope="col">Quantity</th>
          <td scope="col" align="right"><b>Price</b></th>
          <th scope="col">Product Vendor</th>
          <th scop="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for cart in carts %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>

          <td>{{cart.item.product_name}}</td>

          <td>
            <a class="mr-2" href="{% url 'app_cart:decrease' pk=cart.item.pk %}"><span class="badge badge-light"><i class="fas fa-minus text-dark fs-6 me-2"> </i></span></a>
            {{ cart.quantity }}
            <a class="mr-2" href="{% url 'app_cart:increase' pk=cart.item.pk %}"> <span class="badge badge-light"> <i class="fas fa-plus text-dark fs-6 ms-2"></i></span></a>
          </td>

          <td align="right">&#2547; {{cart.get_total}}</td>

          <td>{{cart.item.product_vendor}}</td>

          <td class="d-flex justify-content-center"><a href="{% url 'app_cart:remove' pk=cart.item.pk %}" class="btn btn-danger btn-sm d-felx float-end">Remove From Cart</a></td>
        </tr>
        {% endfor %}
        <tr>
          <th scope="row"></th>
          <td colspan="2">Total</td>
          <td align="right">&#2547; {{order.get_totals | floatformat:2 }}</td>
          <td></td>
        </tr>
      </tbody>
    </table>

    <div class="d-flex justify-content-center mt-5 mb-2">
      <span class="fs-5 ms-5">Gold Coupons: <b style="color: gold;">{{gold}}</b></span>
      <span class="fs-5 mx-5">bronze Coupons: <b style="color: rgb(182, 146, 92);">{{bronze}}</b></span>
    </div>

    <div class="d-flex justify-content-center my-5">
        <a href="{% url 'app_shop:home' %}" class="btn btn-outline-info me-4 px-3">Continue Shoping</a>
        <a href="{% url 'app_payment:checkout' %}" class="btn btn-outline-success ms-4 px-3">Proceed To Checkout</a>
    </div>
</div>
{% endblock body_block %}

eComerce_site/templates/app_cart/coupon.html
{% extends 'base.html' %}
{% block title_block %}{{title}}{% endblock title_block %}
{% block body_block %}
<h1 class="display-4 text-center text-info mt-5 fw-bold">Use your Coupons</h1><hr class="mb-5 shadow">
<div class="mb-5" style="color:rgb(97, 43, 43);">
    <div class="text-center">bronze coupons worth <b>&#2547;25</b>. and gold coupons worth <b>&#2547;250</b></div>
    <div class="text-center">bronze coupons can only be used when buying item priced more than <b>&#2547;25</b>. and for gold coupons is <b>&#2547;250</b></div>
    <div class="text-center">You will get bronze coupons for spending more than <b>&#2547;1000</b>. and gold coupons for spending more than <b>&#2547;10,000</b></div>
</div>
<center>
    <div class="fs-4 text-primary">&#2547;{{total}}</div>
    <div class="fs-5 mb-5">Total Costs</div>

    <div class="d-flex justify-content-center mt-5 mb-3">
        <span class="fs-5 ms-5">Gold Coupons: <b style="color: gold;">{{gold}}</b></span>
        <span class="fs-5 mx-5">bronze Coupons: <b style="color: rgb(182, 146, 92);">{{bronze}}</b></span>
    </div>
    {% if gold < 1 %}
        <div>No Gold Coupons</div>
    {% elif total < 250 %}
        <div>Cannot use Gold Coupons when cost is less than &#2547;250</div>
    {% else %}
    <div class="d-flex justify-content-center my-3">
        <a href="" class="btn btn-outline-warning me-4 px-3">Add Gold Coupon</a>
    </div>
    {% endif %}
    {% if bronze < 1 %}
        <div>No Bronze Coupons</div>
    {% elif total < 25 %}
        <div>Cannot use Bronze Coupons when cost is less than &#2547;25</div>
    {% else %}
    <div class="d-flex justify-content-center my-3">
        <a href="{% url 'app_cart:addBronze' %}" class="btn btn-outline-secondary me-4 px-3">Add Bronze Coupon</a>
    </div>
    {% endif %}

    <div class="d-flex justify-content-center my-3">
        {% if usedBronze > 0 %}
            <a href="{% url 'app_cart:removeBronze' %}" class="btn btn-outline-secondary ms-4 px-3">Remove Bronze Coupon</a>
        {% endif %}
        {% if usedGold > 0 %}
            <a href="" class="btn btn-outline-warning ms-4 px-3">Remove Gold Coupon</a>
        {% endif %}
    </div>

</center>
{% endblock body_block %}