eLearning_site/app_account/urls.py
from django.urls import path
from app_account import views

app_name = "app_account"

urlpatterns = [
    path('registration/', views.registrationView, name='registration'),
    path('login/', views.loginFormView, name='login'),
    path('logout/', views.logoutView, name="logout"),
    path('acc-info/', views.accountInformationView, name="accInfo"),
]

eLearning_site/app_content/urls.py
from django.urls import path
from app_content import views

app_name = "app_content"

urlpatterns = [
    path('', views.homepageView, name="home"),
    path('create-article/', views.ArticleView.as_view(), name="createArticle"),
    path('create-quiz/', views.QuizCreateView, name="createQuiz"),
    path('quiz-list/', views.QuizListView, name="quizList"),
    path('form-post/', views.createForumPostView, name='forumPost'),
    path('forum/', views.forumView, name="forum"),
    path('post/<int:pk>', views.forumPostView, name="post"),
]

eLearning_site/eLearning_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('app_account.urls')),
    path('', include('app_content.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eLearning_site/app_content/models.py
from operator import mod
from django.db import models
from django.contrib.auth.models import User

# Models for Teacher
class Article(models.Model):
    teacher = models.ForeignKey(User, related_name='article_teacher', on_delete=models.CASCADE)
    article_title = models.CharField(max_length=264, verbose_name='Article title')
    article_slug = models.SlugField(max_length=1024, unique=True)
    article_content = models.TextField(verbose_name="Article Content")
    article_img = models.ImageField(upload_to='article_images', verbose_name='Article image', blank=True)
    article_published_date = models.DateTimeField(auto_now_add=True)
    article_update_time = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-article_published_date',]

    def __str__(self) -> str:
        return self.article_title

class Quiz(models.Model):
    teacher = models.ForeignKey(User, related_name='quiz_teacher', on_delete=models.CASCADE)
    quiz_title = models.CharField(max_length=264, verbose_name="Quiz title")
    quiz_content = models.TextField()
    quiz_date = models.DateField()
    total_marks = models.IntegerField()

    class Meta:
        ordering = ['-quiz_date',]

class ForumPost(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="forumPostAuthor")
    post_question = models.CharField(max_length=512)
    post_desc = models.TextField(blank=True)
    post_image = models.ImageField(blank=True)
    post_date = models.DateTimeField(auto_now_add=True)
    post_update_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-post_date',)

    def __str__(self) -> str:
        return self.post_question

class PostAnswer(models.Model):
    post = models.ForeignKey(ForumPost, related_name='forumPostComment', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name= "answerer", on_delete=models.CASCADE)
    answer = models.TextField()
    answer_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('answer_date',)

    def __str__(self) -> str:
        return self.answer

eLearning_site/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'cssFiles/myStyle.css' %}">

    <title>{% block title_block %}Video Site{% endblock title_block %}</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light border shadow-sm sticky-top">
        <div class="container">
            <a class="navbar-brand" href="{% url 'app_content:home' %}"><img class="rounded-circle" id="brand" src="/media/nav_brand.png"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mx-5 mb-2 mb-lg-0">
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    {% if user.is_authenticated %}

                    <li><a class="nav-link" href="{% url 'app_content:forum' %}">Forum</a></li>
                    <div id="acc_type" style="visibility: hidden;">{{user.account_profile.account_type}}</div>
                    <li class="nav-item dropdown" id="teacher">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Teacher options
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'app_content:createArticle' %}">publish article</a></li>
                            <li><a class="dropdown-item" href="{% url 'app_content:createQuiz' %}">Create Quiz</a></li>
                            <li><a class="dropdown-item" href="{% url 'app_content:quizList' %}">All Quizes</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown" id="student">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Student options
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'app_content:quizList' %}">Take a Quiz</a></li>
                            <li><a class="dropdown-item" href="{% url 'app_content:forumPost' %}">Create a forum Post</a></li>
                        </ul>
                    </li>

                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Profile
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="">View Profile</a></li>
                            <li><a class="dropdown-item" href="{% url 'app_account:accInfo' %}">Edit Profile</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class='dropdown-item' href="{% url 'app_account:logout' %}">Logout</a></li>
                        </ul>
                    </li>
                    {% else %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            Login
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'app_account:registration' %}">User Registration</a></li>
                            <li>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'app_account:login' %}">User login</a></li>
                        </ul>
                    </li>
                    {% endif %}
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" name="search" type="search" placeholder="search..." aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>

    <div class='container'>
        {% block body_block %}{% endblock body_block %}
    </div>

    <section class="container-fluid myBackground">
        <div class="container">
            <div class="row">
                <div class="col text-center">
                    <div class="faIcons mx-md-3">
                        <a class="text-decoration-none"
                            href="https://www.youtube.com/channel/UCNtkG_b2gGjUqmyNI9RL3uQ"><i
                                class="fab fa-youtube text-danger"></i></a>
                    </div>
                    <div class="faIcons mx-md-3">
                        <a class="text-decoration-none" href="https://www.facebook.com/AhMunna7x/"><i
                                class="fab fa-facebook-square text-white"></i></a>
                    </div>
                    <div class="faIcons mx-md-3">
                        <a class="text-decoration-none" href="https://twitter.com/munna_ahsanul"><i
                                class="fab fa-twitter text-info"></i></a>
                    </div>
                    <div class="faIcons mx-md-3">
                        <a class="text-decoration-none" href="https://github.com/AH-Munna"><i
                                class="fab fa-github text-white"></i></a>
                    </div>
                </div>
            </div>
            <div class="row text-center text-white">
                <div class="col">
                    <label for="text" class="unselectable">&copy; Copyrights of Ahsanul Haque Munna</label><br>
                    <label for="text" class="unselectable">All Rights Reserved</label>
                </div>
            </div>
        </div>
    </section>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
    <script src="https://kit.fontawesome.com/6bc1f6930c.js" crossorigin="anonymous"></script>

    {% comment %} my script {% endcomment %}
    <script src="{% static 'jsFiles\myScript.js' %}"></script>
</body>

</html>

eLearning_site/templates/index.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load myFilters %}
{% block title_block %}{{title}}{% endblock title_block %}

{% block body_block %}
<a href="#" class="text-center mb-5 d-felx float-end text-decoration-none text-info display-6">{{user.username}}({{user.account_profile.account_type}})</a>

<h1 class='text-center display-4 text-info py-5 my-5'>All the Articles list</h1>
{% for article in article_list %}
    <h3>{{ article.article_title }}</h3>
    created: {{ article.article_published_date }}  updated: {{ article.article_update_time }}
    <br>
    {{ article.article_slug }}

    <div class="row">
        {% if article.article_img %}
            <div class="col-md-4">
                <img src="/media/{{article.article_img}}" alt="{{ article.article_title }}" title="{{ article.article_title }}" width="100%">
            </div>
            <div class="col-md-8">
        {% else %}
            <div class="col">
        {% endif %}
            {{ article.article_content|range_filter_400|linebreaks }}<a class="text-decoration-none" href="">(read more)</a>
            <h6>Posted by: <a class="text-decoration-none" href="#">@{{ article.teacher }}</a></h6>
        </div>
    </div>
    <hr>
{% endfor %}
{% endblock body_block %}